name: coverage

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm run test - --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          directory: ./coverage/
#          token: ${{ secrets.CODECOV_TOKEN }} # Necessary for closed-source projects
